default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food4less_development
  username: munickfreitas
  password: Munick1.

test:
  <<: *default
  database: food4less_test

production:
  primary:
    <<: *default
    database: food4less_production
    username: food4less
    password: <%= ENV["FOOD4LESS_DATABASE_PASSWORD"] %>
    host: <%= ENV["FOOD4LESS_DATABASE_HOST"] %>

  queue:
    <<: *default
    database: food4less_production
    username: food4less
    password: <%= ENV["FOOD4LESS_DATABASE_PASSWORD"] %>
    host: <%= ENV["FOOD4LESS_DATABASE_HOST"] %>

  cache:
    <<: *default
    database: food4less_production
    username: food4less
    password: <%= ENV["FOOD4LESS_DATABASE_PASSWORD"] %>
    host: <%= ENV["FOOD4LESS_DATABASE_HOST"] %>